services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: kth
      POSTGRES_PASSWORD: kth
      POSTGRES_DB: kth
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
